baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-theme-codex"

[params]
  twitter = "https://twitter.com/gustavotiberio"
  github = "https://github.com/gtiberio"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "blog"
  url = "/blog"